# Generated by Django 3.0 on 2021-08-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0004_jugador_preguntasrespondidas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='jugador',
            new_name='jugador_user',
        ),
    ]
