# Generated by Django 3.0 on 2021-08-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0008_auto_20210827_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Puntaje Total'),
        ),
    ]
