# Generated by Django 3.0 on 2021-08-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0011_jugador_mejor_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Maximo Puntaje'),
        ),
    ]
