# Generated by Django 3.0 on 2021-08-31 18:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0012_auto_20210830_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='mejor_puntuacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Mejor Puntuacion'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Puntaje Total'),
        ),
    ]
